# Generated by Django 4.2.5 on 2023-12-11 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreatorprofile',
            name='creator_id',
            field=models.UUIDField(default=uuid.UUID('0fd5055d-d926-4cdd-92c1-2507c24e8ff5')),
        ),
        migrations.AlterField(
            model_name='courseuserprofile',
            name='student_id',
            field=models.UUIDField(default=uuid.UUID('c28d7e14-11ec-435b-ba7f-b5faf4ff83c2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
