# Generated by Django 4.2.5 on 2023-12-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0002_alter_coursecreatorprofile_creator_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=100)),
                ('course_slug', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('course_desc', models.CharField(max_length=200)),
                ('course_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course_discount', models.IntegerField(default=0)),
                ('course_status', models.BooleanField(default=False)),
                ('course_create_date', models.DateTimeField(auto_now_add=True)),
                ('course_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_rating', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('course_user_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('course_tags', models.CharField(default='course', max_length=200)),
                ('course_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.coursecreatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('serial_number', models.IntegerField(default=1)),
                ('video_url_id', models.CharField(max_length=50)),
                ('is_preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.courseuserprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.videolecture')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_progress', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='user_auth.courseuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField(auto_created=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.courseuserprofile')),
            ],
        ),
    ]
